spring:
  redis:
    host: 133.186.244.96
    port: 6379
    database: 18
    password: '*N2vya7H@muDTwdNMR!'
    blackList:
      database: 10
    device:
      database: 13
  session:
    store-type: redis
  profiles:
    active: prod

  spring:
    devtools:
      livereload:
        enabled: true
  freemarker:
    cache: false

